### ISSUE TITLE
Group Deletion

### ISSUE THREAD

**Issue by snippetsam** [NodeBB/nodebb-plugin-write-api#26]
Apologies if this should have been attached to the closed issue. Let me know if that was the case. 

Would it be possible to add deletion of groups to the api? I've changed my local code to test it, so could send a pull request if this would make it easier for you guys? 

Thanks again.

**Comment by snippetsam** [comment]
Also, what would be really useful is a call, with a user ID, to add a user to a group. If the caller has the auth token of an administrator of the group, it bypasses the request / accept process. Something along the lines of: 

/groups
POST /:slug/member
Adds a user to a group (private or not) providing the auth token belongs to an admin of that group
Accepts: uid


This would enable an admin to create a group with people in, on the fly. Again, I'm more than happy to do the leg work on this if required. 

:)

**Comment by julianlam** [comment]
Group deletion, sure. Would accept a PR for that :smile: 

However, adding members to groups isn't a flow that NodeBB allows on the app itself, since it takes the control out of the user's hands, which is why there's no write API endpoint for this.

The library methods are there to enable you to construct a plugin to do so (i.e. `Groups.join` doesn't make any checks), but integrating that into the write API is not something I'm sure of doing.

**Comment by psychobunny** [comment]
Maybe the Write API could have it's own set of hooks for defining more customised / special case endpoints?

**Comment by julianlam** [comment]
Yeah, I'd be open to it. Would want to run it by more people first to see.

**Comment by julianlam** [comment]
v3.0.11, go nuts :smile:
