### ISSUE TITLE
Enable purging topics

### ISSUE THREAD

**Issue by wirepatch** [NodeBB/nodebb-plugin-write-api#71]
So far categories can be purged. In contrast topics may only be deleted (and are thus still visible for e.g. admins).

**Comment by julianlam** [comment]
Hm...

I agree, except for nomenclature purposes, we have

* `DELETE /categories/:cid` which purges
* `DELETE /categories/:cid/state` which disables
* `DELETE /topics/:tid` which deletes (not purge)

I'd change it to use `DELETE /topics/:tid/state` as soft delete... and `DELETE /topics/:tid` as purge, but that means existing users would end up accidentally purging when they want to delete, due to the breaking change in behaviour.

Open to suggestions...

**Comment by wirepatch** [comment]
True, nobody likes breaking existing contracts. What about introducing:

`DELETE /topics/:tid/purge` ?

Which is of course inconsistent with respect to categories.

For the sake of consistency you might redundantly offer:

`DELETE /categories/:cid/purge`

and optionally convey a mid-term policy to withdraw the alias

`DELETE /categories/:cid`

Did I mention **not** being a software architect?

**Comment by julianlam** [comment]
Hey, neither am I, if you want to get technical :smile:

Works for me, will give it a bit more thought

**Comment by wirepatch** [comment]
Sorry for purging my post before seeing your answer: I slightly missed your key argument ...
